# Linter Options
options:
  merge-default-rules: false

# Rule Configuration
rules:
  brace-style:
    - 2
    -
      style: 'stroustrup'
      clean-import-paths: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  no-debug: 1
  no-empty-rulesets: 2
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - 'touch-callout'
        - 'overflow-scrolling'
  no-warn: 1
  one-declaration-per-line: 2
  single-line-per-selector: 2
  trailing-semicolon: 2